version: '3'

services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-${PROJECT_NAME}
    hostname: mysql-${PROJECT_NAME}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT_EXPOSE}:3306"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: pma-${PROJECT_NAME}
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - ${MY_ADMIN_PORT_EXPOSE}:80
  
  backend:
    networks:
      web:
          ipv4_address: ${IP_NEST}
    depends_on:
      - phpmyadmin
    build:
      dockerfile: ./Nest.dockerfile
      context: .
    volumes:
      - ./backend:/usr/src/app/
    command: npm run start:dev
    ports:
      - ${NEST_PORT_EXPOSE}:3000